# Outlook 郵件處理清單

jobs:
  - name: "過濾"
    account: "shigeru777@outlook.com"
    source: "收件匣/microsoft"
    destination: "收件匣/microsoft/processed"
    limit: 10
    plugins:
      - create_appointment
